Update fuel.yml

diff --git a/.github/workflows/fuel.yml b/.github/workflows/fuel.yml
--- a/.github/workflows/fuel.yml
+++ b/.github/workflows/fuel.yml
@@ -25,13 +25,6 @@ jobs:
           CLIENT_ID: ${{ secrets.CLIENT_ID }}
           CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
         run: python fuel_checker.py
-
-      - name: Debug file output
-        run: |
-          echo "Listing files:"
-          ls -l
-          echo "fuel_history.json content:"
-          cat fuel_history.json || echo "File not found"
           
       - name: Test Pushover
         run: |
@@ -63,3 +56,10 @@ jobs:
             git commit -m "Update fuel history"
             git push
           fi
+
+      - name: Debug file output
+        run: |
+          echo "Listing files:"
+          ls -l
+          echo "fuel_history.json content:"
+          cat fuel_history.json || echo "File not found"
